apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: abagesh1904/solar-system-9:37-768e23781b0b01877d73a33db2809753cc3865fb
        name: solar-system
        ports: 
        - containerPort: 80
