apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: abagesh1904/solar-system-9:40-2c75cbb443b36586d188a0e23a18c6434315354f
        name: solar-system
        ports: 
        - containerPort: 80
