apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
  namepsace: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: abagesh1904/solar-system-9:42-f2543f0fa8c6ee3bd1bc23c129df8dea1fd00d0e
        name: solar-system
        ports: 
        - containerPort: 80
