apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: abagesh1904/solar-system-9:36-2b1df49287841f6f01709877bb2583a1383027a1
        name: solar-system
        ports: 
        - containerPort: 80
