apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: abagesh1904/solar-system-9:39-3d8d686f409022df5093c4a21ada302ad24aa309
        name: solar-system
        ports: 
        - containerPort: 80
